import React, { useState, useRef, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PaperPlaneRight, X, Robot } from 'phosphor-react';

// ===== TYPES =====
interface Message {
  id: string;
  text: string;
  sender: 'user' | 'bot';
  timestamp: Date;
}

interface ChatbotProps {
  onSend?: (message: string) => void;
}

// ===== FOCUS TRAP HOOK =====
function useFocusTrap(isActive: boolean) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!isActive) return;

    const container = containerRef.current;
    if (!container) return;

    const focusableElements = container.querySelectorAll<HTMLElement>(
      'button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])'
    );
    const firstElement = focusableElements[0];
    const lastElement = focusableElements[focusableElements.length - 1];

    const handleTabKey = (e: KeyboardEvent) => {
      if (e.key !== 'Tab') return;

      if (e.shiftKey) {
        if (document.activeElement === firstElement) {
          e.preventDefault();
          lastElement?.focus();
        }
      } else {
        if (document.activeElement === lastElement) {
          e.preventDefault();
          firstElement?.focus();
        }
      }
    };

    document.addEventListener('keydown', handleTabKey);
    firstElement?.focus();

    return () => {
      document.removeEventListener('keydown', handleTabKey);
    };
  }, [isActive]);

  return containerRef;
}

// ===== MAIN COMPONENT =====
export default function Chatbot({ onSend }: ChatbotProps) {
  const [isOpen, setIsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);
  const focusTrapRef = useFocusTrap(isOpen);

  const prefersReducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  // Auto-scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Focus input when chat opens
  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [isOpen]);

  // Keyboard handlers
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isOpen) {
        setIsOpen(false);
      }
    };

    document.addEventListener('keydown', handleEscape);
    return () => document.removeEventListener('keydown', handleEscape);
  }, [isOpen]);

  const handleSend = async () => {
    const trimmed = inputValue.trim();
    if (!trimmed) return;

    // Get selected text from session storage if available
    const selectedText = sessionStorage.getItem('selectedText');
    sessionStorage.removeItem('selectedText'); // Clear after use

    const newMessage: Message = {
      id: Date.now().toString(),
      text: trimmed,
      sender: 'user',
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, newMessage]);
    setInputValue('');

    // Show typing indicator
    setIsTyping(true);

    try {
      let response;

      // If there's selected text and the user asks a question, treat it as a selected text query
      if (selectedText && selectedText.trim() && trimmed) {
        response = await fetch('/api/chat/selected', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            question: trimmed,
            selectedText: selectedText,
            sessionId: null, // Will be generated by backend
            userId: null, // Will be filled by backend if user is logged in
          }),
        });
      } else {
        // Full book query
        response = await fetch('/api/chat', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            question: trimmed,
            sessionId: null,
            userId: null,
          }),
        });
      }

      if (!response.ok) {
        throw new Error('Failed to get response from chat API');
      }

      const data = await response.json();
      const botMessage: Message = {
        id: (Date.now() + 1).toString(),
        text: data.response,
        sender: 'bot',
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, botMessage]);
    } catch (error) {
      console.error('Chat API error:', error);
      const botMessage: Message = {
        id: (Date.now() + 1).toString(),
        text: "Sorry, I'm having trouble connecting to the AI service. Please try again later.",
        sender: 'bot',
        timestamp: new Date(),
      };
      setMessages((prev) => [...prev, botMessage]);
    } finally {
      setIsTyping(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <>
      <style jsx>{`
        .chatbot-fab {
          position: fixed;
          bottom: 24px;
          right: 24px;
          width: 56px;
          height: 56px;
          border-radius: 50%;
          background: linear-gradient(135deg, var(--neon-cyan), var(--neon-magenta));
          border: none;
          cursor: pointer;
          display: flex;
          align-items: center;
          justify-content: center;
          box-shadow: 0 4px 20px rgba(0, 242, 255, 0.4);
          z-index: 9998;
          transition: transform 0.2s ease;
        }

        .chatbot-fab:hover {
          transform: scale(1.1);
        }

        .chatbot-fab:active {
          transform: scale(0.95);
        }

        .fab-icon {
          color: var(--raisin-black);
          animation: ${prefersReducedMotion ? 'none' : 'pulse-glow 2s ease-in-out infinite'};
        }

        .fab-icon.open {
          transform: rotate(45deg);
        }

        @keyframes pulse-glow {
          0%, 100% {
            filter: drop-shadow(0 0 4px var(--neon-cyan));
          }
          50% {
            filter: drop-shadow(0 0 12px var(--neon-cyan));
          }
        }

        .chat-window {
          position: fixed;
          bottom: 96px;
          right: 24px;
          width: 380px;
          height: 65vh;
          max-width: 96vw;
          max-height: 600px;
          background: rgba(11, 12, 16, 0.75);
          backdrop-filter: blur(24px);
          border: 1px solid var(--grid-line);
          border-radius: 16px;
          box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
          display: flex;
          flex-direction: column;
          overflow: hidden;
          z-index: 9999;
        }

        .chat-header {
          background: linear-gradient(135deg, rgba(0, 242, 255, 0.1), rgba(255, 0, 193, 0.1));
          padding: 16px;
          display: flex;
          align-items: center;
          gap: 12px;
          border-bottom: 1px solid var(--grid-line);
        }

        .header-icon {
          width: 40px;
          height: 40px;
          border-radius: 50%;
          background: var(--raisin-black);
          display: flex;
          align-items: center;
          justify-content: center;
          border: 1px solid var(--neon-cyan);
        }

        .header-text {
          flex: 1;
        }

        .header-title {
          font-size: 16px;
          font-weight: 700;
          color: #E6E6E6;
          margin: 0;
        }

        .header-subtitle {
          font-size: 12px;
          color: rgba(230, 230, 230, 0.6);
          margin: 0;
        }

        .close-button {
          background: none;
          border: none;
          color: var(--neon-cyan);
          cursor: pointer;
          padding: 4px;
          display: flex;
          align-items: center;
          justify-content: center;
          border-radius: 4px;
          transition: background 0.2s ease;
        }

        .close-button:hover {
          background: rgba(0, 242, 255, 0.1);
        }

        .chat-body {
          flex: 1;
          overflow-y: auto;
          padding: 16px;
          display: flex;
          flex-direction: column;
          gap: 12px;
        }

        .chat-body::-webkit-scrollbar {
          width: 6px;
        }

        .chat-body::-webkit-scrollbar-track {
          background: transparent;
        }

        .chat-body::-webkit-scrollbar-thumb {
          background: var(--grid-line);
          border-radius: 3px;
        }

        .chat-body::-webkit-scrollbar-thumb:hover {
          background: var(--neon-cyan);
        }

        .empty-state {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          color: rgba(230, 230, 230, 0.4);
          text-align: center;
          padding: 24px;
        }

        .empty-state-icon {
          margin-bottom: 12px;
          opacity: 0.3;
        }

        .message-bubble {
          max-width: 80%;
          padding: 12px 16px;
          border-radius: 12px;
          word-wrap: break-word;
          line-height: 1.5;
        }

        .message-user {
          align-self: flex-end;
          background: var(--raisin-black);
          border: 1px solid var(--neon-cyan);
          color: #E6E6E6;
        }

        .message-bot {
          align-self: flex-start;
          background: #011627;
          border: 1px solid var(--neon-magenta);
          color: #E6E6E6;
        }

        .typing-indicator {
          align-self: flex-start;
          display: flex;
          gap: 4px;
          padding: 12px 16px;
          background: #011627;
          border: 1px solid var(--neon-magenta);
          border-radius: 12px;
        }

        .typing-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
          background: var(--neon-magenta);
          animation: ${prefersReducedMotion ? 'none' : 'typing-bounce 1.4s infinite ease-in-out'};
        }

        .typing-dot:nth-child(2) {
          animation-delay: 0.2s;
        }

        .typing-dot:nth-child(3) {
          animation-delay: 0.4s;
        }

        @keyframes typing-bounce {
          0%, 60%, 100% {
            transform: translateY(0);
          }
          30% {
            transform: translateY(-8px);
          }
        }

        .chat-footer {
          padding: 16px;
          border-top: 1px solid var(--grid-line);
          background: rgba(11, 12, 16, 0.5);
        }

        .input-row {
          display: flex;
          gap: 8px;
          align-items: flex-end;
        }

        .chat-input {
          flex: 1;
          background: var(--raisin-black);
          border: 1px solid var(--grid-line);
          border-radius: 8px;
          padding: 10px 12px;
          color: #E6E6E6;
          font-family: var(--ifm-font-family-base);
          font-size: 14px;
          resize: none;
          max-height: 100px;
          transition: border-color 0.2s ease, box-shadow 0.2s ease;
        }

        .chat-input:focus {
          outline: none;
          border-color: var(--neon-cyan);
          box-shadow: 0 0 0 2px rgba(0, 242, 255, 0.2);
        }

        .chat-input::placeholder {
          color: rgba(230, 230, 230, 0.4);
        }

        .send-button {
          background: linear-gradient(135deg, var(--neon-cyan), var(--neon-magenta));
          border: none;
          border-radius: 8px;
          width: 40px;
          height: 40px;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;
          transition: transform 0.2s ease, opacity 0.2s ease;
        }

        .send-button:hover:not(:disabled) {
          transform: scale(1.05);
        }

        .send-button:active:not(:disabled) {
          transform: scale(0.95);
        }

        .send-button:disabled {
          opacity: 0.5;
          cursor: not-allowed;
        }

        .send-icon {
          color: var(--raisin-black);
        }

        @media (max-width: 768px) {
          .chat-window {
            right: 12px;
            bottom: 84px;
            width: calc(100vw - 24px);
          }

          .chatbot-fab {
            right: 12px;
            bottom: 12px;
          }
        }

        @media (prefers-reduced-motion: reduce) {
          .fab-icon,
          .typing-dot {
            animation: none !important;
          }
        }
      `}</style>

      {/* FAB Button */}
      <button
        className="chatbot-fab"
        onClick={() => setIsOpen(!isOpen)}
        aria-label={isOpen ? 'Close AI Tutor Chat' : 'Open AI Tutor Chat'}
      >
        <Robot
          size={28}
          weight="thin"
          className={`fab-icon ${isOpen ? 'open' : ''}`}
        />
      </button>

      {/* Chat Window */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            ref={focusTrapRef}
            className="chat-window"
            role="dialog"
            aria-label="AI Tutor Chat"
            aria-modal="true"
            initial={{ opacity: 0, y: 20, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 20, scale: 0.95 }}
            transition={{
              type: 'spring',
              stiffness: 300,
              damping: 30,
              duration: 0.3,
            }}
          >
            {/* Header */}
            <div className="chat-header">
              <div className="header-icon">
                <Robot size={24} weight="thin" color="var(--neon-cyan)" />
              </div>
              <div className="header-text">
                <h3 className="header-title">AI Tutor</h3>
                <p className="header-subtitle">Ask me anything about Physical AI</p>
              </div>
              <button
                className="close-button"
                onClick={() => setIsOpen(false)}
                aria-label="Close chat"
              >
                <X size={20} weight="bold" />
              </button>
            </div>

            {/* Body */}
            <div className="chat-body">
              {messages.length === 0 ? (
                <div className="empty-state">
                  <Robot size={48} weight="thin" className="empty-state-icon" />
                  <p>Start a conversation with your AI tutor!</p>
                </div>
              ) : (
                <>
                  {messages.map((msg) => (
                    <motion.div
                      key={msg.id}
                      className={`message-bubble ${msg.sender === 'user' ? 'message-user' : 'message-bot'
                        }`}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{
                        type: 'spring',
                        stiffness: 300,
                        damping: 25,
                        duration: 0.2,
                      }}
                    >
                      {msg.text}
                    </motion.div>
                  ))}
                  {isTyping && (
                    <motion.div
                      className="typing-indicator"
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      exit={{ opacity: 0 }}
                    >
                      <div className="typing-dot" />
                      <div className="typing-dot" />
                      <div className="typing-dot" />
                    </motion.div>
                  )}
                </>
              )}
              <div ref={messagesEndRef} />
            </div>

            {/* Footer */}
            <div className="chat-footer">
              <div className="input-row">
                <textarea
                  ref={inputRef}
                  className="chat-input"
                  placeholder="Type your question..."
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyDown={handleKeyDown}
                  rows={1}
                  aria-label="Chat message input"
                />
                <button
                  className="send-button"
                  onClick={handleSend}
                  disabled={!inputValue.trim()}
                  aria-label="Send message"
                >
                  <PaperPlaneRight size={20} weight="bold" className="send-icon" />
                </button>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
}